In [1]:
import epmwebapi as epm
import numpy as np
import datetime

#crie o objeto de conexão informando os endereços do EPM Webserver(Authentication Port e WEB API Port), usuário e senha.
connection = epm.EpmConnection('http://localhost:44333', 'http://localhost:44332', 'sa', 'psw')

bvname = 'ADM_Temperature'

bv = connection.getDataObjects([bvname])

end_date = datetime.datetime.now()
ini_date= end_date - datetime.timedelta(hours=1)
queryPeriod = epm.QueryPeriod(ini_date,end_date)

data = bv[bvname].historyReadRaw(queryPeriod)

In [2]:
# O retorno das funções de leitura da epmwebapi é um ndarray com três campos: Timestamp, Value e Quality.
print(data)

[(24.7, datetime.datetime(2018, 10, 11, 12, 48, 39, tzinfo=datetime.timezone.utc), 0)
 (24.8, datetime.datetime(2018, 10, 11, 12, 50, 39, tzinfo=datetime.timezone.utc), 0)
 (24.9, datetime.datetime(2018, 10, 11, 12, 54, 39, tzinfo=datetime.timezone.utc), 0)
 (25. , datetime.datetime(2018, 10, 11, 12, 59, 19, tzinfo=datetime.timezone.utc), 0)
 (25.1, datetime.datetime(2018, 10, 11, 13, 3, 19, tzinfo=datetime.timezone.utc), 0)
 (25.2, datetime.datetime(2018, 10, 11, 13, 8, 39, tzinfo=datetime.timezone.utc), 0)
 (25.1, datetime.datetime(2018, 10, 11, 13, 11, 19, tzinfo=datetime.timezone.utc), 0)
 (25. , datetime.datetime(2018, 10, 11, 13, 13, 19, tzinfo=datetime.timezone.utc), 0)
 (24.9, datetime.datetime(2018, 10, 11, 13, 13, 59, tzinfo=datetime.timezone.utc), 0)
 (24.8, datetime.datetime(2018, 10, 11, 13, 14, 59, tzinfo=datetime.timezone.utc), 0)
 (24.7, datetime.datetime(2018, 10, 11, 13, 15, 59, tzinfo=datetime.timezone.utc), 0)
 (24.6, datetime.datetime(2018, 10, 11, 13, 16, 59, tzin

In [9]:
# Para acessar os campos use colchetes[]:
print(data['Value'])

[24.7 24.8 24.9 25.  25.1 25.2 25.1 25.  24.9 24.8 24.7 24.6 24.5 24.6
 24.7 24.8 24.9 25.  25.1 25.2 25.1 25.  24.9]


In [13]:
#Para "fatiar" o array usamos a sintaxe array[start:stop:step]. 

#três primeiros valores:
print(data['Value'][0:3])

#do segundo ao quinto valor
print(data['Value'][1:5])

#*O indice da primeira posição do array em Python é zero. 

[24.7 24.8 24.9]
[24.8 24.9 25.  25.1]


In [19]:
#Para calcular valores

#Total
print(data['Value'][0:3].sum())

#Media
print(data['Value'][0:3].mean())

#Desvio Padrão
print(data['Value'][0:3].std())

#adicionar um valor a todos os elementos
print(data['Value'][0:3] + 30)

74.4
24.800001
0.08164919
[54.7 54.8 54.9]
