### Biblioteca Numpy
Numpy adiciona a linguagem Python facilidades para a manipulação e cálculos em arrays de grande dimensão. Ela adiciona o tipo de dado "ndarray", tipo que a epmwebapi utiliza para o retorno de séries temporais do EPM Server.

**Conexão ao EPM Server e busca de dados**

In [4]:
import epmwebapi as epm
import numpy as np
import datetime

#crie o objeto de conexão informando os endereços do EPM Webserver(Authentication Port e WEB API Port), usuário e senha.
connection = epm.EpmConnection('http://localhost:44333', 'http://localhost:44332', 'sa', 'psw')

bvname = 'ADM_Temperature'

bv = connection.getDataObjects([bvname])

end_date = datetime.datetime.now()
ini_date= end_date - datetime.timedelta(hours=1)
queryPeriod = epm.QueryPeriod(ini_date,end_date)

data = bv[bvname].historyReadRaw(queryPeriod)

#Fechando a conexão
connection.close()

In [5]:
# O retorno das funções de leitura da epmwebapi é um ndarray com três campos: Timestamp, Value e Quality.
print(data)

[(23.7, datetime.datetime(2018, 10, 15, 9, 18, 59, tzinfo=datetime.timezone.utc), 0)
 (23.8, datetime.datetime(2018, 10, 15, 9, 28, 39, tzinfo=datetime.timezone.utc), 0)
 (23.9, datetime.datetime(2018, 10, 15, 9, 33, 59, tzinfo=datetime.timezone.utc), 0)
 (24. , datetime.datetime(2018, 10, 15, 9, 39, 19, tzinfo=datetime.timezone.utc), 0)
 (24.1, datetime.datetime(2018, 10, 15, 9, 43, 59, tzinfo=datetime.timezone.utc), 0)
 (24. , datetime.datetime(2018, 10, 15, 9, 50, 59, tzinfo=datetime.timezone.utc), 0)
 (23.9, datetime.datetime(2018, 10, 15, 9, 58, 19, tzinfo=datetime.timezone.utc), 0)]


**Índices**

Os índices começam em zero. E podem ser usados indices negativos, começando em -1, para percorrer o ndarray de trás para frente.

In [8]:
# Para acessar os campos use colchetes[]:
data['Value']

array([23.7, 23.8, 23.9, 24. , 24.1, 24. , 23.9], dtype=float32)

In [14]:
#acessando o primeiro valor do ndarray 
print(data['Value'][0])
#acessando o terceiro valor
print(data['Value'][2])

#acessando o último valor do ndarray 
print(data['Value'][-1])

#acessando o penúltimo valor do ndarray 
print(data['Value'][-2])

23.7
23.9
23.9
24.0


 **Fatiamentos**
 
 Fatiar é a forma de escolher valores dentro do ndarray. Usamos a sintaxe **ndarray[start : stop : step]**

In [25]:
#imprimindo novamente o array para termos a referência de valores
print(data['Value'])

#acessando os dois primeiros elementos
print(data['Value'][0:2])

#acessando o terceiro e quarto elemento
print(data['Value'][2:4])

#acessando os elementos de índice impar
print(data['Value'][1::2])

[23.7 23.8 23.9 24.  24.1 24.  23.9]
[23.7 23.8]
[23.9 24. ]
[23.8 24.  24. ]


**Cálculos**

O Numpy possui diversos métodos que retornam valores cálculados do array.

In [32]:

#Total
print(data['Value'].sum())

#Media
print(data['Value'].mean())

#Desvio Padrão
print(data['Value'].std())

#Valor Máximo
print(data['Value'].max())

#adicionar valor a todos os elementos
print(data['Value'] + 30)


167.4
23.914286
0.12453998
24.1
[53.7 53.8 53.9 54.  54.1 54.  53.9]


**Para mais informações acesse a documentação da biblioteca**

https://docs.scipy.org/doc/numpy/reference/routines.html
